### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by uhlhosting** [DevDavido/performance-audit-plugin#21]
Hi we got:

```
An error occurred
PerformanceAudit plugin activation failed due to the following error: Node.js dependency installation failed due to the following error: NPM has the following unexpected output: npm WARN using --force I sure hope you know what you are doing.npm ERR! code EACCESnpm ERR! syscall mkdirnpm ERR! path /var/www/.npmnpm ERR! errno -13npm ERR! npm ERR! Your cache folder contains root-owned files, due to a bug innpm ERR! previous versions of npm which has since been addressed.npm ERR! npm ERR! To permanently fix this problem, please run:npm ERR! sudo chown -R 33:33 "/var/www/.npm"npm ERR! code EACCESnpm ERR! syscall mkdirnpm ERR! path /var/www/.npmnpm ERR! errno -13npm ERR! npm ERR! Your cache folder contains root-owned files, due to a bug innpm ERR! previous versions of npm which has since been addressed.npm ERR! npm ERR! To permanently fix this problem, please run:npm ERR! sudo chown -R 33:33 "/var/www/.npm"
```

```
root@trace:/home/cosmic# sudo chown -R 33:33 "/var/www/.npm"
chown: cannot access '/var/www/.npm': No such file or directory
```

**Comment by DevDavido** [comment]
Hello, that's a NPM issue, not directly related to the plugin. Have you tried to execute one of the listed suggestions [here](https://stackoverflow.com/questions/59437833/error-your-cache-folder-contains-root-owned-files-due-to-a-bug-in-previous-ver)? And tried to install the plugin afterwards?

**Comment by DevDavido** [comment]
Hello, that's a NPM issue, not directly related to the plugin. Have you tried to execute one of the listed suggestions [here](https://stackoverflow.com/questions/59437833/error-your-cache-folder-contains-root-owned-files-due-to-a-bug-in-previous-ver)? And tried to install the plugin afterwards? The error says the directory `/var/www/.npm` doesn't exist, try also `mkdir /var/www/.npm`.

**Comment by Findus23** [comment]
Hi,

Same happens here. At least on Debian this is to be expected:
- `/var/www/` is oned by `root`, so only it can create directories there
- `/var/www/` is the home of the `www-data` (PHP) user.
- npm tries to create `$HOME/.npm` on the first run which fails because of these two points.

Therefore one has to create `/var/www/.npm` and chown it to the www-data user (`sudo chown www-data:www-data .npm`)

**Comment by DevDavido** [comment]
Do the two answers solve the problem @uhlhosting?

**Comment by DevDavido** [comment]
As I interpret the thumbs up reaction of @uhlhosting as issue solved, I will now close this issue.
