### ISSUE TITLE
Assorted Feedback

### ISSUE THREAD

**Issue by Findus23** [DevDavido/performance-audit-plugin#22]
First of all, many thanks for creating such a useful and ambitious plugin for Matomo.

During install I noticed that chromium depends on `libgbm1`, so you might want to mention this in the docs.

Apart from that the plugin seems to be doing its job well. I tested it with the following:
```
sudo -u www-data php7.3 /var/www/matomo/console  scheduled-tasks:run "Piwik\Plugins\PerformanceAudit\Tasks.auditSite_2"
```
and the task seems to be running well (even though checking every single URL might take some time now).

One thing I noticed: The library seems to be setting `--no-sandbox` for all chromium processes. 
https://github.com/DevDavido/performance-audit-plugin/blob/b14381ec511ffaa65445e896aeba58ae086947b4/vendor/jeroen-g/lighthouse/src/Lighthouse.php#L26
While this is probably needed (I never got lighthouse-cli to work without it on Debian), I am wondering if this might be some security issue if the Matomo administrator doesn't control the tracked sites and should therefore also be documented.

One more thing:
It seems like the archiving throws errors on every 404, which could maybe just be a warning or info as there could be no longer existing sites tracked.

**Comment by DevDavido** [comment]
Thank you @Findus23 for your feedback, I appreciate it. 👍 

> During install I noticed that chromium depends on `libgbm1`, so you might want to mention this in the docs.

I added a [corresponding entry](https://github.com/DevDavido/performance-audit-plugin/commit/33b2ec9ce43af545e145db4a70a53d45f833db8f) to the FAQ docs.


> While this is probably needed (I never got lighthouse-cli to work without it on Debian), I am wondering if this might be some security issue if the Matomo administrator doesn't control the tracked sites and should therefore also be documented.

Same [here](https://github.com/DevDavido/performance-audit-plugin/commit/99e4f0487f764bd56e1eb2e1061e9ac6caeb7100).



> It seems like the archiving throws errors on every 404, which could maybe just be a warning or info as there could be no longer existing sites tracked.

Yes, warning [fits better](https://github.com/DevDavido/performance-audit-plugin/commit/dd5e63e0d11ed339a2e0a4c6bca4eeb34956c15e#diff-e643977fa3ad1b1cee4d42603acb0c44R361) here.

**Comment by Findus23** [comment]
Thanks for the changes: One more weird issue I noticed:

When activating the plugin, non-admin user stop working.
They see
> Ihre Sitzung ist aufgrund Inaktivität abgelaufen. Bitte melden Sie sich an um fortzufahren.
in the UI and
> Sie haben keinen Zugang zu dieser Ressource, weil sie admin Zugriff für mindestens eine Website benötigt
in the API.

Disabling the plugin fixes everything. I am not sure where exactly, but maybe there is some issue with the permissions.

**Comment by DevDavido** [comment]
> Disabling the plugin fixes everything. I am not sure where exactly, but maybe there is some issue with the permissions.

Indeed, there was a typo/bug which will be [fixed](https://github.com/DevDavido/performance-audit-plugin/commit/d32a93d4f9309a2c7a90845f7181e31890f9bf18) in the next release.
