### ISSUE TITLE
Remove anchor in url

### ISSUE THREAD

**Issue by okom3pom** [DevDavido/performance-audit-plugin#33]
Hi,

First, thank you for your excellent work.

What do you think of removing anchors ( Fragment )  from urls ?

Before push a PR i ask you ? 

Sorry for my english.

**Comment by DevDavido** [comment]
Hi, thank you for your kind words :) 
A PR for removing anchors is fine as long as it's performant (as some users have millions of URLs) and is controllable on a per-site setting (as certain sites have frontends which depend on the anchor).
Here's [the part for collecting URLs](https://github.com/DevDavido/performance-audit-plugin/blob/1635df90b3d6259d9ebae5ca4fcb375672e8904f/Tasks.php#L324) and [mainly here for site settings](https://github.com/DevDavido/performance-audit-plugin/blob/main/MeasurableSettings.php).

**Comment by okom3pom** [comment]
I can use a similar method of [groupUrlsByPath](https://github.com/DevDavido/performance-audit-plugin/blob/1635df90b3d6259d9ebae5ca4fcb375672e8904f/Tasks.php#L343)

And i add an config site value similar to [$hasGroupedUrls](https://github.com/DevDavido/performance-audit-plugin/blob/main/MeasurableSettings.php#L36)

Peoples can choose : 

- group url by query string only
- group url by anchor only
- group url by query string and group url by anchor 
- no group 

Say me if the way is ok for you.

**Comment by DevDavido** [comment]
Ok good, maybe you can incorporate the group by URL path setting into a selection of yours like:

Group by...
- path only
- query string only
- anchor only
- path and query string
- path and anchor
- query string and anchor
- path and query string and anchor
- no group

Basically a combination of all possibilities 👍  This would be great!

**Comment by okom3pom** [comment]
I don't understand Group by URL path 

It's only if we want test one url of the path ?

www.mysite.com/boots/my-boots-1.php
www.mysite.com/boots/my-boots-2.php
www.mysite.com/boots/my-boots-3.php

We only test www.mysite.com/boots/my-boots-1.php or www.mysite.com/boots/my-boots-2.php and on the repport we put www.mysite.com/boots/

For anchor it's ok i need to add translations .

![Capture d’écran de 2021-02-09 13-22-57](https://user-images.githubusercontent.com/5064590/107364158-6207ea00-6adb-11eb-87f9-0d63adc04277.png)
