### ISSUE TITLE
Uncontrolled spawning of chrome

### ISSUE THREAD

**Issue by recipedude** [DevDavido/performance-audit-plugin#36]
Activated this plugin.  The next day my matomo server was on its knees.  Took several minutes to shell into the server. Once in I discovered all memory was consumed (12GB, 6 core VM) with a load average of 15.9.

There were 500+ `chrome` processes spun up in parallel!  None of the processes were background or running at a `nice` priority. 

After deactivating the plugin, after about 10 minutes the load on the server returned to a normal level, however there are 500+ 
`/var/www/html/plugins/PerformanceAudit/node_modules/puppeterr/*` idling in the process listing. 

Love the concept of this plugin, however there should be a warning in the description that using it on non-trivial web sites (there will be well over 1/4 million pages under my matomo installation) will need significant planning.  Information on system requirements and would be helpful (based on site size, etc.)

Believe much of what was experienced could be mitigated with additional configuration options that are pre-set at low defaults that will prevent runaway process spawning. 

For example:

- maximum # of pages crawled
- throttle - how many chrome/lighthouse processes will be spun up in parallel
- niceness priority for plugin background processes
- regex configuration options to specify/limit which site pages will be crawled - this could be used to limit the # of pages that will be crawled
- time that plugin will launch the crawl process
- estimate of the # of pages that will get crawled 
- kill switch - ability to immediately terminate any background processes 
- status page 

Update:
Received a massive error email from my matomo server.  Haven't had time to fully review but I can see urls that post only and listed in the robots.txt do not crawl list, along with pages of searches that pass in queries.  

This means that the plugin was trying to lighthouse many of the same endpoints repeatedly each with different search query parameters.  If that is the case my estimate of 1/4 million pages to be crawled will be in the multi-millions!  Can see searches, filtering of results, pagination, sign-up forms; it was even hitting sign-up email validation links!

**Comment by DevDavido** [comment]
Hello, first of all thank you for the detailed feedback. There are some points that I would like to incorporate and improve. These include additional configuration options you mentioned to better control the audit processes, more specific control over which audits are ultimately performed and more information about the expected higher load on the server. However, I also have to mention that some of the statements give a misleading picture. Nothing happens uncontrolled nor with the intention to bring the server to its knees. Rather the opposite: All Lighthouse audit processes start serially one after the other, intentionally not in parallel to keep the load rather low. Lighthouse CLI offers the possibility to set flags for Chrome which are already used by the plugin. If someone could show me how to disable the internal parallel child process spawning of Chrome, I would be pleased. I am also open about PRs for the mentioned improvement suggestions.

**Comment by recipedude** [comment]
Was in no way suggesting there was any _intention_ to bring the server to its knees!  It just happened to work out that way in this particular case. :)

> All Lighthouse audit processes start serially one after the other, intentionally not in parallel to keep the load rather low. 

Wondering how we ended up with 500+ chrome/lighthouse processes running in parallel. 

After deactivating the plugin I let the server chill for an hour, the overall load average dropped quickly but all those processes were still sitting there `ps aux | grep chrome` ... so I ended up doing a `killall chrome` as root and that seems to have cleaned things up with seemingly no harm done. 

Wish I had the spare time to dig into the code.  If I did/do would/will be happy to submit PRs to further the valiant effort so far.

Have a feeling it the plugin works just fine with reasonably sized sites - running it across the millions of tracked dynamic pageviews in this use case was definitely a stress/load test.

**Comment by DevDavido** [comment]
> Wondering how we ended up with 500+ chrome/lighthouse processes running in parallel.

That would definitely require some investigation why it happened.

> Have a feeling it the plugin works just fine with reasonably sized sites - running it across the millions of tracked dynamic pageviews in this use case was definitely a stress/load test.

Yes, that's right, so I [added a section to the README](https://github.com/DevDavido/performance-audit-plugin/tree/4.x-dev#impact-on-server) about the impact on the server and the recommended actions. Sites with over 100,000 tracked unique URLs within the last month might be too big for the plugin architecture.

> Wish I had the spare time to dig into the code. If I did/do would/will be happy to submit PRs to further the valiant effort so far.

Thanks, if you or anyone else wants to submit a PR, here are some [Chrome flags](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md) which might be worth to check out in order to decrease the load further.
