### ISSUE TITLE
Translations using Weblate

### ISSUE THREAD

**Issue by Findus23** [DevDavido/performance-audit-plugin#38]
Hello,

Lukas from Matomo team here. We are currently in the process of moving our translations from Transifex to Weblate (https://github.com/matomo-org/matomo/issues/17907).
As Weblate makes it easier to add a git repository as a component and merge back updated translations via pull requests, I thought it would be great if more plugins in Matomo were available in the users languages if someone is interested in translating them.

If you are interested in adding your plugin, simply comment here, and I'll help you with the setup.

**Comment by DevDavido** [comment]
What exactly is needed to incorporate the plugin to Weblate?

**Comment by Findus23** [comment]
Hi,

Not much. I can create the component at https://hosted.weblate.org/projects/matomo which will import the en.json from this repository. Then you can set up a webhook to `https://hosted.weblate.org/hooks/github/`, so that weblate is immediatly notified of any changes to en.json.

From then on, whenever the translations are updated or a new language is added, Weblate will create (or update) a Pull Request to this repository with the changes, which you can e.g. merge before releases.

**Comment by DevDavido** [comment]
Ok, sounds good to me. 👍

**Comment by Findus23** [comment]
Great, I created the component at https://hosted.weblate.org/projects/matomo/communityplugin-performanceaudit/

The first job adding all languages is already running and created #39.
