### ISSUE TITLE
Matomo 5 compatibility

### ISSUE THREAD

**Issue by snake14** [DevDavido/performance-audit-plugin#44]
Dear Matomo Plugin Author,
We are excited that Matomo 5.0.0 is on the horizon, and we would greatly appreciate your assistance in ensuring that your plugin remains compatible with this upcoming release. Maintaining compatibility will enable Matomo users to seamlessly use your plugin after they upgrade to Matomo 5. (If the plugin is not updated to be compatible with Matomo 5, then whenever a user will upgrade to Matomo 5, the plugin would be automatically disabled to prevent issues.)

Updating your plugin to be Matomo 5 compatible is a straightforward process and should not require a significant time investment. You can find more information about updating your plugin at: https://developer.matomo.org/guides/migrate-matomo-4-to-5

Thank you for your ongoing support and commitment to the Matomo community. 
Your contribution is really appreciated!

The Matomo Team

PS: we’re also available to help if you have any question about making the plugin compatible.

**Comment by snake14** [comment]
Hi @DevDavido . Just a reminder that the Matomo 5 release is fast approaching. Please let me know if you have any questions about making your plugin Matomo 5 compatible.

**Comment by DevDavido** [comment]
Hi @snake14 - I took some time to prepare a beta release for Matomo 5: https://plugins.matomo.org/PerformanceAudit?matomoversion=5
Is there any approval needed from the Matomo team, until this plugin shows up in the Plugin Marketplace search of an Matomo 5 installation?

**Comment by DevDavido** [comment]
Hi @snake14 - I took some time to prepare a release for Matomo 5: https://plugins.matomo.org/PerformanceAudit?matomoversion=5
Is there any approval needed from the Matomo team, until the stable plugin version 3.0.0 shows up in the Plugin Marketplace?

**Comment by snake14** [comment]
Hi @DevDavido . Thank you for making your plugin Matomo 5 compatible.

Sorry about things not updating as expected. In order for Marketplace to pick up the stable version, you need to update the [plugin version in the plugin.json file](https://github.com/DevDavido/performance-audit-plugin/blob/5.x-dev/plugin.json#L4). You might even be able to delete your `3.0.0` tag and release and create them again after updating the plugin.json file, since Marketplace only pays attention to when a new release is created and when the plugin version number has changed.

**Comment by DevDavido** [comment]
Thanks for pointing that out - directly fixed the version in the plugin.json. The Matomo 5 compatible version is available now, therefore I'll close this issue. Feel free to re-open it or leave a comment, if there are any further points to discuss.
