### ISSUE TITLE
How to install it in a shared hosting environment

### ISSUE THREAD

**Issue by hexclann** [DevDavido/performance-audit-plugin#7]
Hey, is it possible to install this plugin on a shared hosting environment. I don't have the root acces and how to solve the npm dependency issue?

**Comment by DevDavido** [comment]
Hi @hexclann, as long as you have Node.js & NPM pre-installed on your shared hosting environment and your PHP configuration allows to execute commands via `proc_open`, it is possible without root access. 

In case that's not possible and enough requests exists, there is a possibility to extend the functionality of this plugin and add external audit services like [Treo](https://treo.sh/) or [KissFront](https://kissfront.com/) for example.
